### ISSUE TITLE
Not reconnecting

### ISSUE THREAD

**Issue by icinger** [bendikwa/igrill#3]
Is it just here, that my iGrillV2 is not reconnecting after a PowerOff?

Besides that, it works great.
Any chance for the future, that we can set a Temperature-Alert?

**Comment by wizbowes** [comment]
Same issue with iGrillV3

**Comment by bendikwa** [comment]
I have also experienced failure to reconnect from time to time. (Although it mostly works for me.) 
I believe the way the Bluetooth communication code is written, it can get into a bad state, where reconnect fails, but I have not had the time to debug it properly.

**Comment by bendikwa** [comment]
I'm closing this due to it being over a year old. I'm guessing you got it working.
If not, please reopen the ticket.

On the feature request for setting temperature alerts, I dont know how to do that. If you get it working, or have an idea on how to do it, open a new issue for this, or submit a PR.

-Bendik
